### ISSUE TITLE
How many abnormalities could your CheXpert classifier output?

### ISSUE THREAD

**Issue by Kingofolk** [ChantalMP/RaDialog#1]
Hi! Thanks a lot for your great work. I am writting to inquiry that how many abnormalities could you CheXpert classifier output? As the CheXpert testset only contains 5 diseases. Looking forward for your reply.
Best regards
Kingofolk

**Comment by ChantalMP** [comment]
Hi,

Thanks for your message!

All our results are macro scores over the entire set of 14 classes, which the Chexpert / Chexbert classifier label (12 pathologies, no finding and support devices).

Best regards,
Chantal

**Comment by Kingofolk** [comment]
Got it. Thanks a lot! wish you a nice day.
Best
Kingofolk
