### ISSUE TITLE
There's a little question in RaDialog/findings_classifier /chexpert_train.py line 216

### ISSUE THREAD

**Issue by novaliulan** [ChantalMP/RaDialog#2]
when you used Class LitIGClassifier,  the args ‘class_names’ and ‘class_weights’ just changed their position, which finally results in the failure of chexpert_train.py

> line 216
> lit_model = LitIGClassifier(num_classes, class_weights, class_names, learning_rate=args.lr)

> line 26
> class LitIGClassifier(pl.LightningModule):
>     def __init__(self, num_classes, class_names, class_weights=None, learning_rate=1e-5):

**Comment by ChantalMP** [comment]
Hey :) You're absolutely right, thanks for letting me know. This must have happened while cleaning the code. I pushed the bug fix.

**Comment by novaliulan** [comment]
Thanks for your nice work
Have a good day~
: )
