### ISSUE TITLE
ModuleNotFoundError: No module named 'health_multimodal' When running the demo

### ISSUE THREAD

**Issue by HosamGen** [ChantalMP/RaDialog#3]
I followed the instructions and added all the weights to the appropriate folders, but I get the following error when trying to run the demo.py command:

```
 from health_multimodal.common.device import get_module_device
ModuleNotFoundError: No module named 'health_multimodal'
```

I cant seem to find the "health_multimodal" anywhere in the repo, so I am not sure if something is missing or I forgot something.

Assistance would be appreciated.

**Comment by ChantalMP** [comment]
Hi,
this sounds like an issue with your environment setup.
After installing all other requirements please install health_multimodal using
`pip install hi-ml-multimodal==0.2.0
`
Afterward to ensure the correct pytorch versions please run
`pip install torch==1.13.0 transformers==4.28.1`

I hope this solves your problem.

Best regards,
Chantal

**Comment by HosamGen** [comment]
Hello,

This indeed fixed the problem, thank you!
