### ISSUE TITLE
--deepspeed ./scripts/zero2.json is missing

### ISSUE THREAD

**Issue by SophieOstmeier** [ChantalMP/RaDialog#4]
Hi Chantal, 
I was wondering if you can also share the deepspeed config.
Thank you so much!
Sophie

**Comment by ChantalMP** [comment]
Hi Sophie,
are you referring to the LLaVA version of RaDialog?
Otherwise please let me know where exactly you encounter deepspeed.
For the LLaVA version, I added the file to [llava/scripts/zero2.json](https://github.com/ChantalMP/RaDialog_LLaVA/blob/master/LLAVA/scripts/zero2.json) :)
Best,
Chantal

**Comment by SophieOstmeier** [comment]
Great, thank you! I will try the LLaVA version with this deepspeed configuration.
