### ISSUE TITLE
Query Regarding Input Shape and Reproduction of Precomputed Embeddings

### ISSUE THREAD

**Issue by hannn0403** [ChantalMP/RaDialog#5]
Hello, I am truly impressed by your research. I attempted to reproduce the precomputed embeddings provided in the code.

However, when I invoked the model using `get_biovil_image_encoder()` and provided an image with a shape of (3, 448, 448) as input, the following output shapes were returned:

`image embedding shape: torch.Size([1, 2048])`
`patch_embeddings shape: torch.Size([1, 2048, 14, 14])`
`projected_global_embedding shape: torch.Size([1, 768])`
`projected_patch_embeddings shape: torch.Size([1, 768, 14, 14])`

**1. Is the input image shape (3, 448, 448) correct?**
**2. The shape of the precomputed embeddings you provided is (32, 768). Which function should I use to reproduce this?**

Thank you.

**Comment by ChantalMP** [comment]
Hi,

An image size of 448 seems to be correct, could you let me know where in the code you are facing this problem? 

Thanks

**Comment by hannn0403** [comment]
I am using a random value called dummy_input to check if the embedding with a shape of (32, 768) is generated. I rewrote the code as follows:
`img_model_t = get_biovil_image_encoder()`
`dummy_input = torch.randn(1, 3, 448, 448)`
`print(f"image embedding shape : {img_model_t(dummy_input).img_embedding.shape}")`
`print(f"patch_embeddings shape : {img_model_t(dummy_input).patch_embeddings.shape}")`
`print(f"projected_global_embedding shape : {img_model_t(dummy_input).projected_global_embedding.shape}")`
`print(f"projected_patch_embeddings shape : {img_model_t(dummy_input).projected_patch_embeddings.shape}")`


When I run this code, I get the following results:

`image embedding shape: torch.Size([1, 2048])`
`patch_embeddings shape: torch.Size([1, 2048, 14, 14])`
`projected_global_embedding shape: torch.Size([1, 768])`
`projected_patch_embeddings shape: torch.Size([1, 768, 14, 14])`

As you can see, the shape is (14, 14), but when I checked the provided pkl file, the shape was (32, 768). Am I missing something?

**Comment by ChantalMP** [comment]
Hi,
I now understand where you come from. This version of RaDialog (this repo) follows a BLIP-style architecture.
Therefore the embeddings are not directly the output of the biovil encoder but the output of the Q-Former module. The Q-Former module is a BERT model that embeds the image information into 32 query embeddings, which is what the shape is coming from.

We published a newer version of RaDialog, which is more straightforward and directly uses the 196 biovil embeddings here: https://github.com/ChantalMP/RaDialog_LLaVA/tree/master
It is a bit more memory intensive, but easier to use.
