### ISSUE TITLE
There's a question in embedding pkl file

### ISSUE THREAD

**Issue by MinJaeKim2796** [ChantalMP/RaDialog#6]
I saved the embeddings of the images in the test set as a pkl file.
Later, while running demo.py, I loaded a specific image as a jpg, computed its embedding.
I found that the embedding value differed from the one in the pkl file corresponding to the same dicom_id.

For the `dicom_id` '18f0fd6d-f513afc9-e4aa8de2-bc5ac0d6-ea3daaff', the first image is the value loaded from the pkl file.
The second image is the value obtained by running `python demo.py --cfg-path pretraining/configs/blip2_pretrain_stage1_emb.yaml`.

![image](https://github.com/user-attachments/assets/d397d715-48cb-489a-a01f-82f38534e4ef)
![image](https://github.com/user-attachments/assets/2c7d0b7b-6233-43b0-b33d-34d99f89b1dc)

When running the code, I got a notice about a warning indicating that the BERT weights were not initialized, as shown below.

![image](https://github.com/user-attachments/assets/ba33f4e5-7eca-4a07-bc96-c303c4b3448e)

I would like to know if this could be the cause of the issue.
Additionally, if there is a separate file for the BERT weights, could you please provide it?

I would appreciate your response. 

Thank you.

**Comment by ChantalMP** [comment]
Hi, 
the warning you are getting is normal. Here () the model is first initialized, the warning is shown, and after that the weights are loaded from checkpoint_4.pth in the weights release.

How did you compute the embeddings of the images in the test set? 
And does the model give a valid-looking answer in the demo?
